### ISSUE TITLE
List Index out of Range

### ISSUE THREAD

**Issue by RakshanPremsagar** [FreeOpcUa/opcua-modeler#103]
Just a beginner, been trying to create an own information model.
But each time, I am getting a index out of range error.
I have tried changing the NodeID's manually as well. 
Still not able to save the xml file.

Please let me know.

-----------------------------------------------------------------------
uamodeler.model_manager - INFO - Starting server on opc.tcp://0.0.0.0:48400/freeopcua/uamodeler/')
uamodeler.server_manager - INFO - Starting python-opcua server')
opcua.server.server - WARNING - Endpoints other than open requested but private key and certificate are not set.')
opcua.server.binary_server_asyncio - WARNING - Listening on 0.0.0.0:48400')
uamodeler.model_manager - INFO - Creating object with args: (NumericNodeId(i=1001), QualifiedName(0:Boiker), Node(NumericNodeId(i=58)))')
uamodeler.model_manager - INFO - Creating variable with args: (NumericNodeId(i=1002), QualifiedName(0:Pressure), Variant(val:0.0,type:VariantType.Double), <VariantType.Double: 11>, NumericNodeId(i=11))')
Gtk-Message: 22:54:42.279: GtkDialog mapped without a transient parent. This is discouraged.
PATH /home/rakshan/Thesis/OpcuaStack/Practise/Boiler
uawidgets.utils - ERROR - list index out of range')
Traceback (most recent call last):
  File "/home/rakshan/.local/lib/python3.6/site-packages/uawidgets/utils.py", line 21, in wrapper
    result = func(self, *args)
  File "/home/rakshan/.local/lib/python3.6/site-packages/uamodeler/uamodeler.py", line 266, in save_as
    self._save_as()
  File "/home/rakshan/.local/lib/python3.6/site-packages/uamodeler/uamodeler.py", line 275, in _save_as
    self._model_mgr.save_xml(path)
  File "/home/rakshan/.local/lib/python3.6/site-packages/uamodeler/model_manager.py", line 219, in save_xml
    self._save_structs()
  File "/home/rakshan/.local/lib/python3.6/site-packages/uamodeler/model_manager.py", line 350, in _save_structs
    urn = self.server_mgr.get_namespace_array()[1]
IndexError: list index out of range
------------------------------------------------------------------------------------------

**Comment by xujiesh0510** [comment]
for anynone who get this error , just  add a namespace 

![image](https://user-images.githubusercontent.com/10271679/108626105-680dab80-7489-11eb-8679-32c2d4c0c73c.png)
