### ISSUE TITLE
Impossible to load default schema `Opc.Ua.Di.NodeSet2.xml`

### ISSUE THREAD

**Issue by danmoser** [FreeOpcUa/opcua-modeler#116]
opcua-modeler returns the error below where loading default schema Opc.Ua.Di.NodeSet2.xml.

Note that asyncua.Server.import_xml() works fine with it.

`opcua                         0.98.13`
`opcua-modeler                 0.5.14`

```
uamodeler.model_manager - INFO - Starting server on opc.tcp://0.0.0.0:48400/freeopcua/uamodeler/')
uamodeler.server_manager - INFO - Starting python-opcua server')
asyncua.server.server - WARNING - Endpoints other than open requested but private key and certificate are not set.')
asyncua.common.xmlparser - WARNING - Parsing value of type 'QualifiedName' not implemented')
asyncua.server.server - WARNING - Deprecated since spec 1.04, call load_data_type_definitions')
asyncua.server.server - WARNING - Deprecated since spec 1.04, call load_data_type_definitions')
asyncua.common.structures - ERROR - Failed to execute auto-generated code from UA datatype: 

@dataclass
class TransferResultDataDataType:

    '''
    TransferResultDataDataType structure autogenerated from xml
    '''

    SequenceNumber:ua.Int32 = 0
    EndOfResults:ua.Boolean = True
    ParameterDefs:List[ua.ParameterResultDataType] = field(default_factory=list)
')
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/common/structures.py", line 281, in _generate_python_class
    exec(code, env)
  File "<string>", line 4, in <module>
  File "<string>", line 12, in TransferResultDataDataType
AttributeError: module 'asyncua.ua' has no attribute 'ParameterResultDataType'
uawidgets.utils - ERROR - module 'asyncua.ua' has no attribute 'ParameterResultDataType'')
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/uawidgets/utils.py", line 21, in wrapper
    result = func(self, *args)
  File "/home/user/.local/lib/python3.8/site-packages/uamodeler/uamodeler.py", line 249, in open
    self._model_mgr.open(path)
  File "/home/user/.local/lib/python3.8/site-packages/uamodeler/model_manager.py", line 184, in open
    self.open_xml(path)
  File "/home/user/.local/lib/python3.8/site-packages/uamodeler/model_manager.py", line 111, in open_xml
    self._open_xml(path)
  File "/home/user/.local/lib/python3.8/site-packages/uamodeler/model_manager.py", line 119, in _open_xml
    self.server_mgr.load_type_definitions()
  File "/home/user/.local/lib/python3.8/site-packages/uamodeler/server_manager.py", line 80, in load_type_definitions
    return self._backend.load_type_definitions()
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/sync.py", line 94, in wrapper
    result = self.tloop.post(aio_func(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/sync.py", line 52, in post
    return futur.result()
  File "/opt/local/stow/python-3.8.2/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/local/stow/python-3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/server/server.py", line 673, in load_type_definitions
    return await load_type_definitions(self, nodes)
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/common/structures.py", line 223, in load_type_definitions
    generator.get_python_classes(structs_dict)
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/common/structures.py", line 177, in get_python_classes
    return _generate_python_class(self.model, env=env)
  File "/home/user/.local/lib/python3.8/site-packages/asyncua/common/structures.py", line 281, in _generate_python_class
    exec(code, env)
  File "<string>", line 4, in <module>
  File "<string>", line 12, in TransferResultDataDataType
AttributeError: module 'asyncua.ua' has no attribute 'ParameterResultDataType'
```

**Comment by danmoser** [comment]
I got the error above trying to "Open" the `Opc.Ua.Di.NodeSet2.xml`. If I create a New Model and then import the XML file, it works.
