### ISSUE TITLE
Unable to save model

### ISSUE THREAD

**Issue by danmoser** [FreeOpcUa/opcua-modeler#117]
I get the following when trying to save a custom model:

```
uawidgets.utils - ERROR - 'NodeId' object has no attribute 'aio_obj'')
Traceback (most recent call last):
  File "/home/dfaes/.local/lib/python3.9/site-packages/uawidgets/utils.py", line 21, in wrapper
    result = func(self, *args)
  File "/home/dfaes/.local/lib/python3.9/site-packages/uamodeler/uamodeler.py", line 266, in save_as
    self._save_as()
  File "/home/dfaes/.local/lib/python3.9/site-packages/uamodeler/uamodeler.py", line 274, in _save_as
    self._model_mgr.save_xml(path)
  File "/home/dfaes/.local/lib/python3.9/site-packages/uamodeler/model_manager.py", line 222, in save_xml
    self._save_structs()
  File "/home/dfaes/.local/lib/python3.9/site-packages/uamodeler/model_manager.py", line 365, in _save_structs
    dict_builder = self._create_type_dict_node(idx, urn, dict_name)
  File "/home/dfaes/.local/lib/python3.9/site-packages/uamodeler/model_manager.py", line 341, in _create_type_dict_node
    if builder.dict_id not in self.new_nodes:
  File "/home/dfaes/.local/lib/python3.9/site-packages/asyncua/sync.py", line 383, in __eq__
    return other is not None and self.aio_obj == other.aio_obj
AttributeError: 'NodeId' object has no attribute 'aio_obj'
```

**Comment by wvalcke** [comment]
I have the same problem....

**Comment by stefanwitkowski** [comment]
I have this issue only if I try to add custom datatype
