### ISSUE TITLE
ImportError: no such module uamodeler.uamodeler

### ISSUE THREAD

**Issue by tanj** [FreeOpcUa/opcua-modeler#53]
Installed from pip version 0.4.0
Tried to run opcua-modeler and got this error:

```

 $ opcua-modeler
 Traceback (most recent call last):
   File "C:\Python27\Scripts\opcua-modeler-script.py", line 9, in <module>
     load_entry_point('opcua-modeler==0.4.0', 'console_scripts', 'opcua-modeler')()
   File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
     return get_distribution(dist).load_entry_point(group, name)
   File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
     return ep.load()
   File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
     return self.resolve()
   File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
     module = __import__(self.module_name, fromlist=['__name__'], level=0)
 ImportError: No module named uamodeler.uamodeler
```

uamodeler module is missing the `__init__.py` file to allow it to be imported as a module.

**Comment by oroulet** [comment]
Some python2 stuff. Modeller is written for python3.
