### ISSUE TITLE
Ubuntu 16.04 / opcua-modeler fails to start after installing

### ISSUE THREAD

**Issue by 6guenther** [FreeOpcUa/opcua-modeler#83]
I am not quite sure what's my problem is here, tried installing the modeler using `pip3 install opcua-modeler` and got the following error message:
```Traceback (most recent call last):
  File "/home/ros/.local/bin/opcua-modeler", line 7, in <module>  
    from uamodeler.uamodeler import main  
  File "/home/ros/.local/lib/python3.5/site-packages/uamodeler/uamodeler.py", line 15, in <module>  
    from uawidgets.attrs_widget import AttrsWidget  
  File "/home/ros/.local/lib/python3.5/site-packages/uawidgets/attrs_widget.py", line 11, in <module>  
    from uawidgets.get_node_dialog import GetNodeButton  
  File "/home/ros/.local/lib/python3.5/site-packages/uawidgets/get_node_dialog.py", line 7, in <module>  
    from uawidgets.tree_widget import TreeWidget  
  File "/home/ros/.local/lib/python3.5/site-packages/uawidgets/tree_widget.py", line 62  
    raise ValueError(f"Node {node} not found in tree")  
```

OS is Ubuntu 16.04 
PyQt5 is installed

**Comment by zerox1212** [comment]
You need Python 3.6 or higher. You are using 3.5.

**Comment by 6guenther** [comment]
Fixed it, thanks for the quick reply!

**Comment by oroulet** [comment]
Can you make a pull request?

**Comment by zerox1212** [comment]
I edited the ReadMe to clarify this point. It has been in the Issues a few times.
